apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: writer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: writer
    spec:
      containers:
      - name: writer
        image: docker.io/cytram/messaging-system-writer:0.1.0
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        volumeMounts:
        - name: output-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: tail
        image: alpine:3.14
        command: ["tail"]
        args: ["-f", "/data/output.txt"]
        volumeMounts:
        - name: output-volume
          mountPath: /data
      volumes:
      - name: output-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: writer
spec:
  selector:
    app.kubernetes.io/name: writer
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: writer
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: writer
